### PR TITLE
Game logic Milestone

### PR DESCRIPTION
**Pull request by daviidy**
we used the minimax algorithm with alpha-beta enhancement

### CODE REVIEW

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey **David Yao & Dawood Dawood** <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:28.025851938895418% 91.95064629847238%;background-size:5418.75% 5418.75%" data-codepoints="1f44b-1f3ff"></span></span> 

The game logic is really impressive. I'm impressed by your correct utilization of modules and classes. <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:97.94359576968273% 95.94594594594594%;background-size:5418.75% 5418.75%" data-codepoints="2714-fe0f"></span></span> <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:20.035252643948294% 55.99294947121034%;background-size:5418.75% 5418.75%" data-codepoints="1f3c5"></span></span> 
It is also impressive how you implemented the AI. This is way beyond what was required for this project. Great work team <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:30.0235017626322% 38.01410105757932%;background-size:5418.75% 5418.75%" data-codepoints="1f44f-1f3ff"></span></span> 

However, I found a bug and a couple of other things that need fixing.

### Changes Required <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:95.94594594594594% 53.99529964747356%;background-size:5418.75% 5418.75%" data-codepoints="267b-fe0f"></span></span> 

- [x] The AI keeps overriding my move in one of the play scenes. I couldn't find a way of explaining this without writing a whole paragraph or taking photos of every turn. so I decided to make you a loom video. Find it here https://www.loom.com/share/2fe09827639946b5917bc6cf95ed46ad

- [x] Also, commit messages like `fix some issue` and `add changes` are not acceptable <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:95.94594594594594% 75.96944770857814%;background-size:5418.75% 5418.75%" data-codepoints="26a0-fe0f"></span></span> . Read more about how and why to make better commits here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Unprofessional commits are reason enough to render your Project invalid, requiring you to start afresh. Please consider this in your next milestone and future projects.

**NOTE:** You didn't need to create a new pull request and every time a TSE requests changes and you make them, please add a comment stating what you worked on. 

Please make the suggested changes and resubmit for review. Otherwise impressive work. Keep it up <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:30.0235017626322% 14.042303172737954%;background-size:5418.75% 5418.75%" data-codepoints="1f44d-1f3ff"></span></span> 

Happy Coding <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:59.9882491186839% 85.95769682726204%;background-size:5418.75% 5418.75%" data-codepoints="1f60e"></span></span> 

For any assistance or clarification, find me on slack as **Phillip Musiime**

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey **David Yao & Dawood Dawood**

### Changes Required ♻️ 

I see you have made some improvements to your code. Asking for the player's name and assigning them a "piece" as you have called it. Great improvement.

However, you didn't address the major bug I found in your code the first time. I refer you to this video again please watch it carefully and fix this issue.
https://www.loom.com/share/2fe09827639946b5917bc6cf95ed46ad 

If you need further clarification please reach out to me on slack as **Phillip Musiime**

Happy Coding 😎

**Comment by daviidy** [comment]
Now it's fixed

**Review by Georjane — CHANGES_REQUESTED** [review]
# Status: Changes Required🔂
## Hi there @MohameDawood and @daviidy🙌 

You guys have done a great job with the Tic tac toe project.👏👏 This is really amazing, being able to play with an automated player. Nice work!👍🎉
But i came across the same problem the previous TSE encountered. I think the bug🐛 happened for me when I entered the number 8, it rather marked number 3 instead of 8, and then when I choose 8 again which shows unmarked on the board it says position taken. Then when I enter 3 which is a position already taken according to the display on the board, it rather marks 8. So the problem might be coming from the display of the board 🔢 but I am not so sure. It is a little hard to explain but check out the screenshot of your game when I tried playing.
Please check this out and work on it, then you can submit another Code Review.
Happy Coding💻
Feel free to reach out to me on slack: **Witah Georjane**

bug

**Review by Georjane — CHANGES_REQUESTED** [review]
## Hello again team!🙌
I only just realized that your board is being displayed from **9 to 1** instead of **1 to 9**. If you can change this so it will be less confusing for the players or you can display the actual numbers on the board, so the players can see which numbers are available to choose from. That will be very nice. 

I think if you adjust this, we will not have any issues playing your game smoothly!
Thank you 👍

**Review by Georjane — APPROVED** [review]
# Status: PR Approved ✔️
## Congratulations team🎉🎉🎊
Good job. Your project is perfect now. You can go ahead and merge this PR. 

Goodluck on your next project 👍 and Happy Coding 💻

**Pull request merged**
